# Generated by Django 5.0 on 2023-12-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprice',
            name='product_key',
        ),
        migrations.AddField(
            model_name='dealerprice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_prices', to='products.product'),
        ),
    ]
