# Generated by Django 5.0 on 2023-12-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_dealerprice_product_key_dealerprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprice',
            name='dealer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dealer'),
        ),
    ]
