# Generated by Django 5.0 on 2023-12-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_dealerprice_dealer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprice',
            name='product',
        ),
        migrations.AddField(
            model_name='dealerprice',
            name='product_key',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dealerprice',
            name='dealer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_prices', to='products.dealer'),
        ),
    ]
