# Generated by Django 4.2.4 on 2023-12-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productdealerkey_choices_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_markup_count', models.IntegerField()),
                ('none_chosen_count', models.IntegerField()),
                ('choices_order', models.IntegerField()),
            ],
        ),
    ]
