# Generated by Django 5.0 on 2023-12-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_dealerprice_product_dealerprice_product_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealer_prices',
            field=models.ManyToManyField(related_name='products', to='products.dealerprice'),
        ),
    ]
