# Generated by Django 5.0 on 2023-12-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_dealer_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dealer_prices',
        ),
    ]
