# Generated by Django 5.0 on 2023-12-06 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_dealer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealerprice',
            old_name='dealer_id',
            new_name='dealer_name',
        ),
    ]
