# Generated by Django 5.0 on 2023-12-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_dealer_id_dealerprice_dealer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdealerkey',
            old_name='dealer_id',
            new_name='dealer_name',
        ),
    ]
