# Generated by Django 5.0 on 2023-12-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_dealer_id_productdealerkey_dealer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealerprice',
            old_name='dealer_name',
            new_name='dealer_id',
        ),
        migrations.RenameField(
            model_name='productdealerkey',
            old_name='dealer_name',
            new_name='dealer_id',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
